export type SemanaData = {
  semana: number;
  fruta: string;
  frutaEmoji: string;
  articulo: 'un' | 'una';
  peso: string;
  talla: string;
  desarrollo: string[];
  sintomas: string[];
  curiosidad: string;
};

export const DESARROLLO_POR_SEMANA: Record<number, SemanaData> = {
  4:  { semana: 4,  fruta: 'Semilla de amapola', frutaEmoji: '🌱', articulo: 'una', peso: '< 1 g',   talla: '0.1 cm', desarrollo: ['Implantación completa en el útero', 'Se forman las tres capas germinales del embrión', 'El corazón primitivo comienza a formarse', 'Se inicia el desarrollo del tubo neural'], sintomas: ['Posible retraso menstrual', 'Sensibilidad en los senos', 'Fatiga leve'], curiosidad: 'Aunque es del tamaño de una semilla de amapola, el embrión ya tiene toda la información genética necesaria para desarrollarse.' },
  5:  { semana: 5,  fruta: 'Semilla de sésamo',  frutaEmoji: '🌾', articulo: 'una', peso: '< 1 g',   talla: '0.2 cm', desarrollo: ['El corazón comienza a latir por primera vez', 'Se forman los brotes de brazos y piernas', 'El tubo neural se cierra', 'Aparecen los órganos principales'], sintomas: ['Náuseas matutinas', 'Senos muy sensibles', 'Fatiga intensa'], curiosidad: 'El corazón del bebé late entre 80 y 100 veces por minuto, ¡el doble que el tuyo!' },
  6:  { semana: 6,  fruta: 'Lenteja',            frutaEmoji: '🫘', articulo: 'una', peso: '< 1 g',   talla: '0.6 cm', desarrollo: ['Se forman los ojos y los oídos', 'El corazón tiene 4 cámaras', 'Aparecen los dedos de manos y pies', 'Se desarrolla el intestino y los pulmones'], sintomas: ['Náuseas y vómitos frecuentes', 'Aversión a olores', 'Mareos'], curiosidad: 'A pesar de ser tan pequeño, el corazón del bebé ya late entre 100 y 160 veces por minuto.' },
  7:  { semana: 7,  fruta: 'Arándano',           frutaEmoji: '🫐', articulo: 'un',  peso: '< 1 g',   talla: '1.0 cm', desarrollo: ['El cerebro crece a gran velocidad', 'Se forman los párpados', 'Los pulmones toman forma', 'Aparece el apéndice y el páncreas'], sintomas: ['Náuseas intensas', 'Salivación excesiva', 'Cambios de humor frecuentes'], curiosidad: 'El cerebro del bebé genera 100 nuevas células nerviosas por minuto en esta etapa.' },
  8:  { semana: 8,  fruta: 'Frambuesa',          frutaEmoji: '🍓', articulo: 'una', peso: '1 g',     talla: '1.6 cm', desarrollo: ['Todos los órganos vitales están presentes', 'El bebé se mueve aunque no se siente aún', 'Se forman los genitales', 'Los dedos están casi separados'], sintomas: ['Fatiga extrema', 'Náuseas persistentes', 'Estreñimiento'], curiosidad: 'El bebé ya puede doblar los brazos y las muñecas, aunque sus movimientos son imperceptibles.' },
  9:  { semana: 9,  fruta: 'Aceituna',           frutaEmoji: '🫒', articulo: 'una', peso: '2 g',     talla: '2.3 cm', desarrollo: ['Los dientes comienzan a formarse bajo las encías', 'Se desarrollan los músculos', 'Los párpados cubren los ojos', 'El corazón late 170 veces por minuto'], sintomas: ['Acidez estomacal', 'Mareos al levantarse', 'Cambios en el apetito'], curiosidad: 'El bebé ya tiene huellas dactilares únicas, ¡ninguna igual en el mundo!' },
  10: { semana: 10, fruta: 'Ciruela',            frutaEmoji: '🍑', articulo: 'una', peso: '4 g',     talla: '3.1 cm', desarrollo: ['Los órganos vitales ya funcionan', 'El bebé puede tragar líquido amniótico', 'Se forman las uñas', 'El cerebro produce 250.000 neuronas por minuto'], sintomas: ['Reducción gradual de náuseas', 'Ligero aumento de energía', 'Acidez frecuente'], curiosidad: 'Esta semana el período fetal comienza: ya no es un embrión sino un feto con todas sus estructuras formadas.' },
  11: { semana: 11, fruta: 'Lima',               frutaEmoji: '🍋', articulo: 'una', peso: '7 g',     talla: '4.1 cm', desarrollo: ['Los genitales se pueden distinguir', 'El bebé puede hacer muecas', 'Se forman los folículos pilosos', 'Los huesos comienzan a endurecerse'], sintomas: ['Menos náuseas', 'Aumento del apetito', 'Hinchazón abdominal leve'], curiosidad: 'El bebé abre y cierra las manos y ya puede chuparse el pulgar.' },
  12: { semana: 12, fruta: 'Limón',              frutaEmoji: '🍋', articulo: 'un',  peso: '14 g',    talla: '5.4 cm', desarrollo: ['Los reflejos están presentes', 'Los riñones producen orina', 'El intestino se mueve al abdomen', 'La médula ósea produce glóbulos blancos'], sintomas: ['Posible reducción total de náuseas', 'Mayor energía', 'Ligero aumento de peso'], curiosidad: 'El bebé puede chuparse el dedo y ya tiene su propio tipo de sangre.' },
  13: { semana: 13, fruta: 'Durazno',            frutaEmoji: '🍑', articulo: 'un',  peso: '23 g',    talla: '7.4 cm', desarrollo: ['Las huellas dactilares están completamente formadas', 'El bebé orina en el líquido amniótico', 'Los intestinos se mueven al interior del abdomen', 'Los ojos se mueven hacia el frente'], sintomas: ['Más energía general', 'Posible aparición de la línea alba', 'Senos más grandes'], curiosidad: '¡Comienza el segundo trimestre! La etapa más cómoda y emocionante del embarazo.' },
  14: { semana: 14, fruta: 'Limón grande',       frutaEmoji: '🍋', articulo: 'un',  peso: '43 g',    talla: '8.7 cm', desarrollo: ['El bebé puede fruncir el ceño y sonreír', 'El cuello se alarga', 'Aparece el lanugo (vello corporal fino)', 'El hígado produce bilis'], sintomas: ['Reducción de síntomas molestos', 'Posible aumento del deseo sexual', 'Encías sensibles'], curiosidad: 'El bebé ya hace expresiones faciales completas dentro del útero.' },
  15: { semana: 15, fruta: 'Manzana',            frutaEmoji: '🍎', articulo: 'una', peso: '70 g',    talla: '10.1 cm', desarrollo: ['El bebé puede escuchar sonidos externos', 'Los huesos se endurecen con calcio', 'Se desarrolla el sentido del gusto', 'Los ojos responden a la luz'], sintomas: ['Posibles dolores de espalda', 'Congestión nasal', 'Mayor energía y vitalidad'], curiosidad: '¡El bebé puede escuchar tu voz por primera vez! Háblale, ya te reconoce.' },
  16: { semana: 16, fruta: 'Aguacate',           frutaEmoji: '🥑', articulo: 'un',  peso: '100 g',   talla: '11.6 cm', desarrollo: ['El sistema nervioso se conecta con los músculos', 'El bebé hace movimientos de respiración', 'Los ojos pueden moverse bajo los párpados', 'Las trompas de Falopio o el escroto están formados'], sintomas: ['Posibles primeros movimientos del bebé', 'Dolor de ligamentos redondos', 'Piel más luminosa'], curiosidad: 'Algunas mamás sienten los primeros movimientos como mariposas en el estómago o burbujas.' },
  17: { semana: 17, fruta: 'Pera',               frutaEmoji: '🍐', articulo: 'una', peso: '140 g',   talla: '13.0 cm', desarrollo: ['Se acumula grasa bajo la piel del bebé', 'El cordón umbilical se hace más grueso', 'El corazón bombea 25 litros de sangre al día', 'Se forman las articulaciones'], sintomas: ['Aumento de peso notable', 'Posibles hemorroides', 'Congestión nasal frecuente'], curiosidad: 'El bebé puede escuchar los sonidos de tu digestión y tu latido del corazón.' },
  18: { semana: 18, fruta: 'Pimiento',           frutaEmoji: '🫑', articulo: 'un',  peso: '190 g',   talla: '14.2 cm', desarrollo: ['El bebé reconoce tu voz y reacciona a ella', 'Se forman las características del rostro', 'El útero o los ovarios están completamente formados', 'El bebé tiene ciclos de sueño y vigilia'], sintomas: ['Posible dolor de ligamentos', 'Mareos al levantarse rápido', 'Aumento notable del apetito'], curiosidad: 'Si es niña, ya tiene 6 millones de óvulos en sus diminutos ovarios.' },
  19: { semana: 19, fruta: 'Mango',              frutaEmoji: '🥭', articulo: 'un',  peso: '240 g',   talla: '15.3 cm', desarrollo: ['El cerebro designa áreas para los sentidos', 'Aparece el vernix caseosa (capa protectora blanca)', 'El bebé duerme y se despierta en ciclos', 'Los riñones filtran orina activamente'], sintomas: ['Dolor de espalda', 'Hinchazón de pies al final del día', 'Posible síndrome de piernas inquietas'], curiosidad: 'El vernix caseosa es una capa blanca que protege la piel del bebé del líquido amniótico.' },
  20: { semana: 20, fruta: 'Plátano',            frutaEmoji: '🍌', articulo: 'un',  peso: '300 g',   talla: '16.4 cm', desarrollo: ['¡Mitad del embarazo!', 'El bebé traga líquido amniótico activamente', 'Los movimientos son más fuertes y frecuentes', 'Se puede identificar el sexo claramente en ecografía'], sintomas: ['Movimientos del bebé claramente sentidos', 'Dolor en la pelvis', 'Acidez frecuente'], curiosidad: '¡Estás en la mitad del camino! El bebé ya tiene cejas, pestañas y puede bostezar.' },
  21: { semana: 21, fruta: 'Zanahoria grande',   frutaEmoji: '🥕', articulo: 'una', peso: '360 g',   talla: '26.7 cm', desarrollo: ['El bebé se despierta con ruidos fuertes', 'El bazo produce glóbulos rojos', 'Los movimientos son más coordinados', 'El sistema digestivo practica con el líquido amniótico'], sintomas: ['Posible hinchazón de tobillos', 'Calambres en las piernas por la noche', 'Umbigo que sobresale'], curiosidad: 'El bebé puede sentir cuando tocas tu barriga y puede responder moviéndose.' },
  22: { semana: 22, fruta: 'Papaya',             frutaEmoji: '🍈', articulo: 'una', peso: '430 g',   talla: '27.8 cm', desarrollo: ['Los sentidos del tacto se desarrollan', 'El bebé tiene ciclos de sueño-vigilia regulares', 'Los labios y cejas están bien definidos', 'El páncreas produce insulina'], sintomas: ['Posible aparición de estrías', 'Dolores en la ingle', 'Mayor apetito'], curiosidad: 'El bebé puede sentir el ritmo de la música y calmarse con melodías suaves.' },
  23: { semana: 23, fruta: 'Mango grande',       frutaEmoji: '🥭', articulo: 'un',  peso: '500 g',   talla: '28.9 cm', desarrollo: ['Los pulmones producen surfactante', 'El bebé tiene movimientos oculares rápidos (sueña)', 'La piel es arrugada y rojiza', 'Escucha y responde a sonidos del exterior'], sintomas: ['Dolores de espalda más frecuentes', 'Posible prueba de glucosa', 'Hinchazón general'], curiosidad: '¡El bebé llega a los 500 gramos! Sus pulmones se preparan para respirar aire.' },
  24: { semana: 24, fruta: 'Mazorca de maíz',    frutaEmoji: '🌽', articulo: 'una', peso: '600 g',   talla: '30.0 cm', desarrollo: ['Los pulmones producen surfactante para respirar', 'El bebé tiene cejas y pestañas completas', 'Reacciona a la luz con movimientos', 'El cerebro crece muy rápido'], sintomas: ['Contracciones de Braxton Hicks', 'Posible dificultad para dormir', 'Acidez intensa'], curiosidad: 'A partir de esta semana el bebé podría sobrevivir fuera del útero con cuidados médicos intensivos.' },
  25: { semana: 25, fruta: 'Nabo',               frutaEmoji: '🫚', articulo: 'un',  peso: '660 g',   talla: '34.6 cm', desarrollo: ['El cabello del bebé crece y tiene color', 'La médula espinal produce glóbulos rojos', 'El bebé puede responder al dolor', 'Los pulmones siguen madurando'], sintomas: ['Acidez muy frecuente', 'Hemorroides posibles', 'Venas varicosas en piernas'], curiosidad: 'El bebé tiene ciclos de sueño de 20 a 40 minutos, igual que un recién nacido.' },
  26: { semana: 26, fruta: 'Lechuga',            frutaEmoji: '🥬', articulo: 'una', peso: '760 g',   talla: '35.6 cm', desarrollo: ['Los ojos comienzan a abrirse por primera vez', 'El sistema inmune se desarrolla', 'Las huellas dactilares están completamente formadas', 'El cerebro responde a estímulos externos'], sintomas: ['Dolores de espalda intensos', 'Dificultad para respirar', 'Posible insomnio'], curiosidad: '¡El bebé puede ver luz a través del vientre! Ilumina tu barriga y verá un resplandor rosado.' },
  27: { semana: 27, fruta: 'Coliflor',           frutaEmoji: '🥦', articulo: 'una', peso: '875 g',   talla: '36.6 cm', desarrollo: ['El cerebro crece y forma nuevos pliegues', 'El bebé reconoce voces familiares', 'El sistema nervioso madura rápidamente', 'Los pulmones siguen desarrollando alvéolos'], sintomas: ['Mayor incomodidad general', 'Más contracciones de Braxton Hicks', 'Dificultad para dormir boca arriba'], curiosidad: '¡Comienza el tercer y último trimestre! La recta final hacia conocer a tu bebé.' },
  28: { semana: 28, fruta: 'Berenjena',          frutaEmoji: '🍆', articulo: 'una', peso: '1.0 kg',  talla: '37.6 cm', desarrollo: ['Los pulmones pueden respirar aire con ayuda', 'El bebé parpadea y tiene reflejos visuales', 'El cerebro tiene pliegues bien definidos', 'El lanugo comienza a desaparecer'], sintomas: ['Dolores de cadera', 'Dificultad para dormir', 'Mayor frecuencia urinaria'], curiosidad: '¡El bebé ya pesa un kilogramo! Ha multiplicado su peso por mil desde la semana 10.' },
  29: { semana: 29, fruta: 'Calabaza',           frutaEmoji: '🎃', articulo: 'una', peso: '1.15 kg', talla: '38.6 cm', desarrollo: ['Los huesos están completamente desarrollados', 'El bebé acumula grasa corporal', 'Puede ver y escuchar con claridad', 'El cerebro controla la temperatura corporal'], sintomas: ['Dificultad para respirar', 'Acidez intensa', 'Hinchazón notable en pies y manos'], curiosidad: 'El bebé ya tiene aproximadamente el 15% de grasa corporal que lo mantendrá caliente al nacer.' },
  30: { semana: 30, fruta: 'Melón pequeño',      frutaEmoji: '🍈', articulo: 'un',  peso: '1.3 kg',  talla: '39.9 cm', desarrollo: ['El cerebro desarrolla surcos y pliegues', 'El bebé distingue la luz de la oscuridad', 'Los pulmones siguen madurando', 'Almacena hierro, calcio y fósforo'], sintomas: ['Calambres frecuentes en las piernas', 'Dificultad para caminar', 'Agotamiento general'], curiosidad: 'El bebé llena casi todo el espacio del útero y sus patadas se sienten con mucha fuerza.' },
  31: { semana: 31, fruta: 'Coco',               frutaEmoji: '🥥', articulo: 'un',  peso: '1.5 kg',  talla: '41.1 cm', desarrollo: ['Los pulmones están casi maduros', 'El bebé procesa información visual', 'El iris tiene ya su color definitivo', 'Todos los sentidos están activos'], sintomas: ['Presión pélvica', 'Frecuente necesidad de orinar', 'Contracciones más frecuentes'], curiosidad: 'Los ojos del bebé pueden seguir una fuente de luz que se mueva sobre tu barriga.' },
  32: { semana: 32, fruta: 'Piña',               frutaEmoji: '🍍', articulo: 'una', peso: '1.7 kg',  talla: '42.4 cm', desarrollo: ['El bebé practica movimientos de respiración', 'Las uñas llegan a las puntas de los dedos', 'El lanugo desaparece casi por completo', 'El esqueleto está casi totalmente formado'], sintomas: ['Dificultad para respirar', 'Insomnio frecuente', 'Mayor incomodidad general'], curiosidad: 'El bebé duerme entre el 90 y 95% del tiempo, acumulando energía para el gran día.' },
  33: { semana: 33, fruta: 'Piña grande',        frutaEmoji: '🍍', articulo: 'una', peso: '1.9 kg',  talla: '43.7 cm', desarrollo: ['El bebé detecta luz y oscuridad con precisión', 'Los huesos del cráneo no están fusionados para el parto', 'Acumula grasa rápidamente', 'El sistema inmune recibe anticuerpos de la mamá'], sintomas: ['Vientre muy prominente', 'Dificultad al agacharse', 'Ansiedad por el parto'], curiosidad: 'Los huesos del cráneo del bebé son flexibles para facilitar el paso por el canal de parto.' },
  34: { semana: 34, fruta: 'Melón cantalupo',    frutaEmoji: '🍈', articulo: 'un',  peso: '2.1 kg',  talla: '45.0 cm', desarrollo: ['El sistema nervioso central madura', 'El bebé abre y cierra los ojos con facilidad', 'Reconoce canciones que escuchó durante el embarazo', 'Los pulmones casi completamente maduros'], sintomas: ['Falsa alarma de trabajo de parto', 'Hinchazón de manos y pies', 'Dificultad para dormir'], curiosidad: 'El bebé puede reconocer la canción de cuna que le cantaste durante todo el embarazo.' },
  35: { semana: 35, fruta: 'Calabaza mediana',   frutaEmoji: '🎃', articulo: 'una', peso: '2.4 kg',  talla: '46.2 cm', desarrollo: ['Los riñones están completamente desarrollados', 'El hígado puede procesar algunos residuos', 'El bebé está tomando posición para el parto', 'Acumula grasa a razón de 250g por semana'], sintomas: ['Presión pélvica intensa', 'Dificultad para caminar', 'Hinchazón notable'], curiosidad: 'El bebé podría nacer esta semana con muy pocas o ninguna complicación.' },
  36: { semana: 36, fruta: 'Papaya grande',      frutaEmoji: '🍈', articulo: 'una', peso: '2.6 kg',  talla: '47.4 cm', desarrollo: ['El bebé pierde el lanugo', 'Acumula grasa muy rápidamente', 'Los pulmones casi completamente maduros', 'Practica la succión y deglución constantemente'], sintomas: ['Encajamiento del bebé en la pelvis', 'Más facilidad para respirar', 'Mayor presión pélvica'], curiosidad: 'El bebé ya tiene suficiente grasa para regular su propia temperatura corporal al nacer.' },
  37: { semana: 37, fruta: 'Acelga',             frutaEmoji: '🥬', articulo: 'una', peso: '2.85 kg', talla: '48.6 cm', desarrollo: ['¡El bebé es considerado a término!', 'Los pulmones están completamente maduros', 'Practica la succión y deglución', 'El cerebro sigue desarrollándose'], sintomas: ['Contracciones más frecuentes e intensas', 'Posible pérdida del tapón mucoso', 'Mezcla de ansiedad y emoción'], curiosidad: '¡El bebé ya está listo para nacer! Cada día que pasa suma madurez a su cerebro.' },
  38: { semana: 38, fruta: 'Sandía pequeña',     frutaEmoji: '🍉', articulo: 'una', peso: '3.1 kg',  talla: '49.8 cm', desarrollo: ['El cerebro y los pulmones siguen madurando', 'El bebé produce meconio (primera deposición)', 'Se prepara activamente para el nacimiento', 'Acumula anticuerpos de la mamá'], sintomas: ['Contracciones irregulares frecuentes', 'Posible pérdida del tapón mucoso', 'Dificultad para caminar'], curiosidad: 'El bebé está en posición cefálica, con la cabeza hacia abajo, listo para el gran momento.' },
  39: { semana: 39, fruta: 'Sandía',             frutaEmoji: '🍉', articulo: 'una', peso: '3.3 kg',  talla: '50.7 cm', desarrollo: ['El bebé está completamente desarrollado', 'Acumula anticuerpos de la mamá', 'La piel está suave y rosada', 'El cerebro sigue creciendo activamente'], sintomas: ['Contracciones que pueden ser de parto', 'Espera ansiosa y emocionada', 'Mucha incomodidad general'], curiosidad: 'Al nacer, el bebé reconocerá tu voz al instante, ¡te ha escuchado durante meses!' },
  40: { semana: 40, fruta: 'Sandía grande',      frutaEmoji: '🍉', articulo: 'una', peso: '3.5 kg',  talla: '51.2 cm', desarrollo: ['El bebé está completamente desarrollado', 'El sistema inmune recibió todos tus anticuerpos', 'El corazón late 130 veces por minuto', 'Listo para respirar, comer y conocerte'], sintomas: ['¡Es el gran día!', 'Contracciones regulares y progresivas', 'Ruptura de membranas posible'], curiosidad: 'El bebé reconocerá tu voz, tu olor y tu tacto al instante de nacer. ¡Todo el amor que le diste, lo recibió!' },
};
